### ISSUE TITLE
Online Subscription

### ISSUE THREAD

**Issue by AdamChlan** [sonnetmedia/hudsonreview.com#4]
They would like to migrate their current subscription payment form to one that creates a user account/subscription. The will likely offer the following options:

- Online Only
- Print and Online (where they will mail the issue as well)

Currently they offer SOME content for free:
https://hudsonreview.com/issue/winter-2020/

The print version has all the content. They would like to offer a paywalled version of the full content online.

The currently use Paypal as their processor. Will need to make sure their version supports subscriptions, and may be worthwhile exploring moving them over to Stripe.

They are looking for a ballpark quote they can use for a grant they are applying for.

**Comment by budparr** [comment]
so, is this a "buddypress" situation?

**Comment by AdamChlan** [comment]
Thinking MemberPress. Similar, but much simpler than NBCC, because there would be no migration. I would just see us onboard members via the form, but not importing any existing members, because they are not currently using subscription functionality.

**Comment by budparr** [comment]
so guestimate for hours? Would we need to change their hosting?

**Comment by AdamChlan** [comment]
No change in hosting. They have the CloudFlare cert. The MemberPress they would need is current $150 (on sale?). With yearly renewals that would likely be in that range...possibly more if it's truly on sale. It might always be on sale though. I can confirm with them.

Hours would likely be around 8.

**Comment by budparr** [comment]
wow, that's it? I would have thought 2x or 3x that. And, we should think about the potential for increased maintenance expense - more moving pieces, and people's money flowing around.

**Comment by AdamChlan** [comment]
Yeah, I could definitely see the need for more monthly support time for them.

I likely should allot more time for project management, revisions, etc. 16-20 would likely be a safer number.

**Comment by budparr** [comment]
Alright. I guess memberpress does a lot of the heavy lifting. So let's set a budget of 3k and tell them that maintenance will need to increase from 85/mo to 125 per month. Do you think that's reasonable? That allows for an additional 5ish hours per year.

**Comment by AdamChlan** [comment]
Yes, that all sounds good. I can send an email over today and CC you on it, or would you prefer to send?

**Comment by budparr** [comment]
You can send it. Thank you.

**Comment by AdamChlan** [comment]
Paula replied and said this was a good number for the allowed budget. I'm going to have a follow up call with them at 10am tomorrow, as they wanted to bring another team member into the fold to make sure he didn't have anything additional to add. Certainly I will flag anything that would impact the budget and we can review.

**Comment by budparr** [comment]
Oh, good. Thank you.

**Comment by AdamChlan** [comment]
I checked in on the scheduling for this one, and this was the reply:

**_We should hear about the grant on or before July 1 and will be back to you then._**

**Comment by AdamChlan** [comment]
unfortunately my follow up on this has gone unanswered so thinking they may not have got the grant or are still waiting to hear.

**Comment by budparr** [comment]
Interesting. Understandable about the possibility of the grant going away, but odd they wouldn't reply.

**Comment by AdamChlan** [comment]
This project is now active. I am trying to set up a time to have a call with the HR team to get things rolling.

**Comment by AdamChlan** [comment]
Meeting set w/ Hudson Review for Nov 5 to discuss details of membership and content needed for site.

**Comment by AdamChlan** [comment]
hold on to your hat....this is live.
