### ISSUE TITLE
Quote work for Eileen

### ISSUE THREAD

**Issue by AdamChlan** [sonnetmedia/hudsonreview.com#6]
--Redesign/ update of website to match our new cover (font, colors, etc.), and making it easy to change the background color of the homepage every season to match the issue (I imagine this is something I would do manually when uploading a new issue) **Adam would plan on rolling out a new theme based on Roots / Tailwind. Existing content would come over as is. The issues data model would remain that same, but the layout could change in a way the data model will support. Bud would build a Hugo / Tailwind version and Adam would apply to the templates. - 12 hours**

**Items below would likely happen regardless of the redesign**

--Make images and videos automatically scale when accessing site on mobile devices - **1 hour**

--Creation of an archive very similar to HR Poets Online, "Critics Online." 50 critics' pieces in full, available for free to all visitors. -  **4 hours**

--Create a "subscribe to digital editions" box on homepage - **1/2 hour**

--Create "join our newsletter" form on homepage (we are about to create a weekly newsletter)  - **1/2 hour**

--Addition of a form onto the Writers in the Schools page, so teachers can apply to participate in the program. - **1/2 hour**

--Addition of a news column on the homepage -  **1/2 hour**

--Removal of Note from the Editor and books column from homepage - **1/2 hour**

--Make image of issue cover bigger on homepage - **1/2 hour**

**Comment by AdamChlan** [comment]
@budparr I added some time estimates to this work

**Comment by budparr** [comment]
I'll close this. Thank you!
